# Generated by Django 3.0.6 on 2020-06-16 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goldswancamcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(1984, 5, 17, 0, 0))),
                ('timeCC', models.TimeField(default=datetime.time(12, 0))),
                ('dealer', models.IntegerField(default=0)),
                ('pickup', models.IntegerField(default=0)),
                ('rnd', models.IntegerField(default=0)),
                ('smallGal', models.IntegerField(default=0)),
                ('squareGal', models.IntegerField(default=0)),
                ('dealCust', models.IntegerField(default=0)),
                ('dayparts', models.TextField(blank=True)),
                ('suspectText', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kalcamcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(1984, 5, 17, 0, 0))),
                ('timeCC', models.TimeField(default=datetime.time(12, 0))),
                ('dealer', models.IntegerField(default=0)),
                ('pickup', models.IntegerField(default=0)),
                ('rnd', models.IntegerField(default=0)),
                ('smallGal', models.IntegerField(default=0)),
                ('squareGal', models.IntegerField(default=0)),
                ('dealCust', models.IntegerField(default=0)),
                ('dayparts', models.TextField(blank=True)),
                ('suspectText', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labcamcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(1984, 5, 17, 0, 0))),
                ('timeCC', models.TimeField(default=datetime.time(12, 0))),
                ('dealer', models.IntegerField(default=0)),
                ('pickup', models.IntegerField(default=0)),
                ('rnd', models.IntegerField(default=0)),
                ('smallGal', models.IntegerField(default=0)),
                ('squareGal', models.IntegerField(default=0)),
                ('dealCust', models.IntegerField(default=0)),
                ('dayparts', models.TextField(blank=True)),
                ('suspectText', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tmbcamcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(1984, 5, 17, 0, 0))),
                ('timeCC', models.TimeField(default=datetime.time(12, 0))),
                ('dealer', models.IntegerField(default=0)),
                ('pickup', models.IntegerField(default=0)),
                ('rnd', models.IntegerField(default=0)),
                ('smallGal', models.IntegerField(default=0)),
                ('squareGal', models.IntegerField(default=0)),
                ('dealCust', models.IntegerField(default=0)),
                ('dayparts', models.TextField(blank=True)),
                ('suspectText', models.TextField(blank=True)),
            ],
        ),
    ]
