# Generated by Django 3.0.5 on 2020-04-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctvcounter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='date_posted',
            new_name='join_date',
        ),
    ]
