# Generated by Django 3.0.5 on 2020-04-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctvcounter', '0002_auto_20200425_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='join_date',
            field=models.DateTimeField(),
        ),
    ]
