# Generated by Django 3.0.5 on 2020-04-25 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctvcounter', '0003_auto_20200425_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(1993, 8, 5, 0, 0)),
        ),
    ]
