# Generated by Django 3.0.6 on 2020-05-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessreport', '0002_auto_20200525_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalimpreport',
            name='supplyIns',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='supplyIns',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tmbreport',
            name='supplyIns',
            field=models.TextField(blank=True),
        ),
    ]
